### DISCUSSION TITLE
关于脚注符号 & 标题层级 & 警告块 | footnote symbol & header level visibility & alert block

### DISCUSSION THREAD

**Discussion by One-In-Dark** [liangjingkanji/DrakeTyporaTheme#168] [General]
> 使用 drake-black, 可以说是梦中情CSS了!

### PART1 Question

非常感谢作者的贡献! Many thanks to your contribution!

有些小问题: 有点好奇为什么脚注 `.md-def-name:after` 被设计成 `.^` 呢? 看上去怪怪的 😢 

为什么 `.MathJax` 使用 120% 字大小啊, 这样不会凸起来吗 😢 

### PART2 Sharing

我对 `h2`, `h3` 标题样式做了调整, 可以方便地看到层级. `h4` 恢复了默认 `:focus` 设置. 下面是这些东西的代码:
```css
h2 span {
    border-bottom: 2px solid #80543C;
}
h3::before {
    content: '>'!important;
    margin-right: 4px;
    color: #B97A57!important;
}
h3.md-focus::before {
    border: none;
    position: inherit;
    float: inherit;
    padding: 0 0 0 0;
    font-size: inherit;
    vertical-align: inherit;
    font-weight: inherit;
    left: 0;
    top: 0;
}
```

标题的间距似乎有点过大了. 可以将
```css
h1,
h2,
h3,
h4,
h5,
h6 {
    … (omitted)
    margin-top: 2rem;
    … (omitted)
}
```

改成 `1rem`, 然后对 `h1` 单独设置 `margin-top: 1rem`.

最后对 GitHub 风格的警告块调整了行间距, 因为「note」等字样与首行文字真的离太远了 😃
```css
div.md-alert>p:first-child {
    margin-bottom: 0.2em;
}
div.md-alert>p:nth-child(2) {
    margin-top: 0;
}
```
