### ISSUE TITLE
设置图片居左

### ISSUE THREAD

**Issue by imshi** [liangjingkanji/DrakeTyporaTheme#101]
### 描述问题
- 正文中插入的图片默认居中，请问怎么设置可以让图片居左显示呢？[Typora Support](https://support.typora.io/Images/) 中提供的如下配置没有作用
```css
p .md-image:only-child{
    width: auto;
    text-align: left;
}
```

### 如何复现问题
 - 同问题描述

### 期望结果
- 插入的图片居左显示

### 截图
![image](https://user-images.githubusercontent.com/16249566/185726374-3b44fb96-9c95-45f4-a617-6543f78d3f52.png)

### 系统 (建议使用最新Typora版本)
 - OS：windows 11
 - Theme：Drake
 - Typora Version：v1.3.6
