### ISSUE TITLE
更改 font.css 去符号黏连 无效

### ISSUE THREAD

**Issue by domeniczz** [liangjingkanji/DrakeTyporaTheme#103]
### 描述问题
更改 font.css 去符号黏连 无效

现在更改完以后，只有代码块和标题里面的字体是 jetbrain mono 的，正文的不是期望的 jetbrain mono nl

以下是我更改后的 font.css

```css
...
/* **** 以下四个 @font-face 是我自己添加 **** */
@font-face {
    font-family: 'JetBrainsMonoNL';
    src: local('JetBrainsMonoNL'),
    url('./JetBrainsMonoNL-Regular.ttf') format('ttf');
    font-display: swap;
    font-weight: normal;
    font-style: normal;
}
@font-face {
    font-family: 'JetBrainsMonoNL';
    src: local('JetBrainsMonoNL'),
    url('./JetBrainsMonoNL-Italic.ttf') format('ttf');
    font-display: swap;
    font-weight: normal;
    font-style: italic;
}
@font-face {
    font-family: 'JetBrainsMonoNL';
    src: local('JetBrainsMonoNL'),
    url('./JetBrainsMonoNL-Bold.ttf') format('ttf');
    font-display: swap;
    font-weight: bold;
    font-style: normal;
}
@font-face {
    font-family: 'JetBrainsMonoNL';
    src: local('JetBrainsMonoNL'),
    url('./JetBrainsMonoNL-BoldItalic.ttf') format('ttf');
    font-display: swap;
    font-weight: bold;
    font-style: italic;
}

:root {
    --monospace: "JetBrainsMonoNL", "JetBrains Mono", "Fira Code", "Cascadia Code", Menlo, "Ubuntu Mono", Consolas, HYZhengYuan; /*代码字体*/
    /* **** 更改了以下两行 **** */
    --text-font: var(JetBrainsMonoNL); /*正文字体*/
    --title-font: var(--monospace); /*标题字体*/
    
    --text-line-height: 1.6; /*正文行间距*/
    --code-block-line-height: 1.6; /*代码块行间距*/
    --p-spacing: 0.8rem; /*段间距*/
    --text-size: 12px;
}
```

jetbrain mono 的 zip 包下载下来后，有 NL 的字体只有 tff格式，我复制进了 drake 目录中

### 期望结果

正文的字体是 jetbrain mono nl

### 系统 (建议使用最新Typora版本)
 - windows 22H2 build 22622.586
 - All Theme
 - Typora Version 1.3.8
