### ISSUE TITLE
能否设置Latex公式的字体？

### ISSUE THREAD

**Issue by sleepingraven** [liangjingkanji/DrakeTyporaTheme#105]
### 描述问题

可以设置Latex公式预览中文字体

### 期望结果

<img width="869" alt="2022-09-10_153724" src="https://user-images.githubusercontent.com/32897701/189474241-0e1480dc-0d87-4a25-b533-fcaf47c56266.png">

### 截图

<img width="870" alt="2022-09-10_153756" src="https://user-images.githubusercontent.com/32897701/189474247-7829ec05-27b1-4dc2-ad90-5348dd325bc9.png">

### 系统
 - OS: Win11
 - Theme: drake-google
 - Typora Version: 1.4.3

### 思路

Typora 在公式的<code>text</code>标签设置了行内属性<code>font-family="serif"</code>，所以可以设置标签的字体：

``` css
.MathJax text {
    font-family: var(--text-font);
}
```

### 其他

是否可以单独设置中文字体，比如：

``` css
:root {
    --monospace: "Fira Code", var(--zhff);
    --zhff: HYZhengYuan;
    --textff: Times, var(--zhff), serif;
    --text-font: var(--textff);
    --title-font: var(--textff);
    …
}
```

经过测试，代码的字体依然用了<code>--monospace</code>。
