### ISSUE TITLE
一级标题居中

### ISSUE THREAD

**Issue by osmondy-yang** [liangjingkanji/DrakeTyporaTheme#107]
### 描述问题
默认设置的一级标题居中吗？

### 期望结果
希望一级标题不居中

### 截图
![image](https://user-images.githubusercontent.com/29267453/190340393-0b737bd6-dfa3-4265-8ef3-4ee0263566c6.png)

### 系统 (建议使用最新Typora版本)
 - OS: MacOS 12.5
 - Theme: Drake 
 - Typora Version: 1.3.7 (6424)

**Comment by liangjingkanji** [comment]
设计如此, 你可以参考官方文档修改主题

**Comment by osmondy-yang** [comment]
> 设计如此, 你可以参考官方文档修改主题

感谢答复。
我找到解决办法了。
修改xxx.css文件，注释（或去掉） `text-align: center;`，重启Typora即可。
```css
...
h1 {
    font-size: 2rem;
    /* text-align: center; */
    margin-top: 0;
}
...
```
