### ISSUE TITLE
修改字体后，导出的pdf样式失效？

### ISSUE THREAD

**Issue by huangjingling** [liangjingkanji/DrakeTyporaTheme#157]
### 描述问题
修改font.css文件中的字体为宋体，然后带出pdf的样式有点问题。
好像是加粗失效了。
``` css
:root {
    --monospace: "JetBrains Mono", "Fira Code", "Cascadia Code", Menlo, "Ubuntu Mono", Consolas, "宋体", HYZhengYuan; /*代码字体*/
    --text-font: var(--monospace); /*正文字体*/
    --title-font: var(--monospace); /*标题字体*/
    --text-line-height: 2.0; /*正文行间距*/
    --code-block-line-height: 1.6; /*代码块行间距*/
    --p-spacing: 0.8rem; /*段间距*/
}
```

### 如何复现问题
修改font.css文件中的字体为宋体。

### 截图
截图左边是导出的pdf，右边是typora里面。
![image](https://github.com/liangjingkanji/DrakeTyporaTheme/assets/68362495/13717305-a65f-499f-adc7-f00995c5af41)

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version
