### ISSUE TITLE
mac上使用seamless外观模式，文档树显示异常

### ISSUE THREAD

**Issue by darkmanno6** [liangjingkanji/DrakeTyporaTheme#26]
ver：版本0.11.2 (5601)
同级目录也展示成了子目录
![image](https://user-images.githubusercontent.com/8080262/129467341-7e0e0318-3f24-4173-81dc-e001755a4531.png)

把以下css样式注掉了就正常了。

```css
.mac-seamless-mode #typora-sidebar {
    font-size: 1rem;
}
```
