### ISSUE TITLE
导出的 html 和 在 Typora 中, 字体显示效果不一致

### ISSUE THREAD

**Issue by voncin** [liangjingkanji/DrakeTyporaTheme#53]
### 描述问题

导出的 html 中代码字体变成了加粗斜体
### 期望结果
正常使用 JetBrain Mono 字体

### 截图
![image](https://user-images.githubusercontent.com/68265597/151275582-491733cd-aa34-4cb0-a63d-5ccc42ce09a3.png)

### 系统 (建议使用最新Typora版本)
 - OS : win11
 - Theme 
 - Typora Version: 测试版最后一版

### 尝试
- 在主题中添加:
`@include-when-export url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap');`
- 另外: 
退出源码模式的按钮有些违和, 添加:
```css
.typora-sourceview-on #toggle-sourceview-btn{
    background-color: var(--item-hover-bg-color);
}
```
