### ISSUE TITLE
请问怎么修改代码块代码的间距呀？

### ISSUE THREAD

**Issue by YuXuan7198** [liangjingkanji/DrakeTyporaTheme#58]

**Comment by liangjingkanji** [comment]
你搜索`code block`, 然后在下面的样式添加`line-height: 2rem`

```css
/*code block*/
.md-fences {
    font-size: 1rem;
    padding: 0.5rem !important;
    border-radius: 2px;
    word-wrap: normal;
    line-height: 2rem; 添加行高
    background-color: var(--code-block-bg-color);
    color: var(--code-block-color);
    border: none;
}
```
