### ISSUE TITLE
本地图片显示太大

### ISSUE THREAD

**Issue by jipiyan** [liangjingkanji/DrakeTyporaTheme#62]
### 描述问题
图片显示太大，每次调整zoom比较麻烦

### 如何复现问题
插入大分辨本地图片

### 期望结果
对img样式的max-height作出调整限制最大高度
或者其他更好的方式
```css
img {
    border-left: none;
    border-right: none;
    vertical-align: baseline;
    border-radius: 0.5rem;
    max-height: 480px;
}
```

### 截图
**谢谢您的主题，用着很舒服**

### 系统 (建议使用最新Typora版本)
 - OS MacOS 11.6.3
 - Theme Drake Ayu
 - Typora Version 1.0.5
