### ISSUE TITLE
如何修改代码片段内外间距问题

### ISSUE THREAD

**Issue by xiaochen0517** [liangjingkanji/DrakeTyporaTheme#65]
### 描述问题
这个行内代码的内外边距是哪个属性，调大字体时候代码块变大两个都重叠了。

### 截图
![image](https://user-images.githubusercontent.com/30149408/155639930-0bf45855-002a-4060-ab7d-46cc1332b8fd.png)

**Comment by liangjingkanji** [comment]
```css
/*code snippet*/
#write code, tt {
    margin: 0 2px;
    border-radius: 2px;
    color: var(--drake-highlight);
    background-color: #fff5f5;
    padding: .065em .4em;
}
```
margin 即外边距 padding 内边距
