### ISSUE TITLE
如何设定正文的行间距?

### ISSUE THREAD

**Issue by dongbingliu** [liangjingkanji/DrakeTyporaTheme#69]
### 描述问题
如何设定正文的行间距?

### 期望结果
设置自定义的行间距

### 系统 (建议使用最新Typora版本)
 - OS
 - Theme 
 - Typora Version

**Comment by liangjingkanji** [comment]
修改`**.css`主题文件内容
```css
body {
  /*...*/
  line-height: 1.8rem; /*正文行高*/
}
```
