### ISSUE TITLE
二级标题样式修改

### ISSUE THREAD

**Issue by ChrisGray0626** [liangjingkanji/DrakeTyporaTheme#72]
### 描述问题

希望能修改二级标题的样式，比如字体大小。

其他标题的修改都比较常规，唯独这个标题不是很明白怎么修改，应该是您加了下划线这个特殊样式吧。

能力有限，不吝赐教。

```css
h2 .md-plain {
    padding-bottom: .3rem;
    border-bottom: .2rem solid var(--h2-underline-color);
    line-height: 3rem;
}

.on-focus-mode h2.md-end-block.md-heading:not(.md-focus):not(.md-focus-container):after {
    background-color: var(--blur-text-color) !important;
}
```

**Comment by liangjingkanji** [comment]
你更新下主题, 我已经显式指定`h2`文字大小

搜索以下可以找到
```css
h2 {
    font-size: 1.8rem;
}
```
