### ISSUE TITLE
修改字体大小

### ISSUE THREAD

**Issue by liangjingkanji** [liangjingkanji/DrakeTyporaTheme#83]
## 全局字体配置
关于字体大小你可以在设置界面设置, 不使用`自动`即可

<img src="https://user-images.githubusercontent.com/21078112/131225124-f51ccf14-8093-4dd0-a42f-52680cede82c.png" width="70%"/>

### 正文字体大小

如果只想修改本主题字体大小请打开`font.css`修改`--text-size`
```css
--text-size: 12px;
```

### 代码字体大小

```css
/*code block*/
.md-fences {
    font-size: 1rem; /*代码字体大小*/
}
```

### 标题字体大小

比如修改h1标题就搜索`h1 {`

```css
h1 {
    font-size: 2rem; /*字体大小, 改为20px 或者2rem(两倍普通文字大小)*/
    text-align: center;
    margin-top: 0;
}
```

标题h2/h3...以此修改
