### ISSUE TITLE
导出成pdf后二级标题没有下划线，并且最左边的数字序号会被截断。

### ISSUE THREAD

**Issue by moulai** [liangjingkanji/DrakeTyporaTheme#85]
### 描述问题
在typora中预览正常，导出PDF后，二级标题下没有了下划线，并且最左边的两位数的数字序号会被截掉，经查看，该数字序号仍然存在（可以选中），但是上面覆盖了一层白色。
在.css文件中，将`max-width: 1200px;`修改为`max-width: 97%;`后，数字序号被截断的问题解决了，但是依然没有二级标题的下划线。

### 如何复现问题

在typora中输入：
<img width="814" alt="image" src="https://user-images.githubusercontent.com/8275836/166140282-b1324455-cd18-4d48-b135-a8ac8820fa5f.png">

导出成PDF后（序号不正常，二级标题不正常）：

<img width="747" alt="image" src="https://user-images.githubusercontent.com/8275836/166140294-0615cf32-2727-479a-ad91-95b3ca7ed90a.png">

**注意最下方的序号应该是10和11而非0和1。**

导出成HTML后（序号正常，二级标题不正常）：

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/8275836/166140333-fec97cd3-8bbc-468d-b396-70ec5deb45a9.png">

### 系统 (建议使用最新Typora版本)
 - OS：MacOS Monterey 12.3.1
 - Theme ：Drake Vue
 - Typora Version：1.2.4
 - 已安装所有需要的字体

**Comment by moulai** [comment]
@liangjingkanji Drake主题真的非常美观实用，感谢您的工作~

**Comment by liangjingkanji** [comment]
这个你得给Typora官方提issue了，主题无法解决

**Comment by liangjingkanji** [comment]
@moulai 也欢迎你贡献新的主题风格

**Comment by moulai** [comment]
> 这个你得给Typora官方提issue了，主题无法解决

好的，谢谢您！

**Comment by moulai** [comment]
@liangjingkanji 
我发现似乎是因为在生成html文件时，typora并**没有**给生成的`<span>二级标题</span>`加上`md-plain`类（由于pdf是通过html导出的，因此也有同样的问题），使得以下css样式失效：
```css
h2 .md-plain {
    padding-bottom: .3rem;
    border-bottom: .2rem solid var(--h2-underline-color);
    line-height: 3rem;
}
```
typora生成的html文件：
```html
<h2 id='二级标题'><span>二级标题</span></h2>
```
我把drake.css文件中所有的`.md-plain`替换成`span`后，问题解决了，但是这应该不是恰当的解决方式，请问怎样修改比较合适呢？

**Comment by liangjingkanji** [comment]
你的二级标题出现问题了吗?

**Comment by moulai** [comment]
> 你的二级标题出现问题了吗?

是的，在问题描述中有截图，typora中二级标题有下划线，但导出成html和pdf后没有下划线了。

**Comment by liangjingkanji** [comment]
我是说你删除md-plain以后是不是二级标题不正常了，这种删除问题我觉得会导致很多样式变更吧，我感觉还是Typora官方本身输出完整样式可能更好

**Comment by moulai** [comment]
> 我是说你删除md-plain以后是不是二级标题不正常了，这种删除问题我觉得会导致很多样式变更吧，我感觉还是Typora官方本身输出完整样式可能更好

没有，我在Drake.css中，把所有`.md-plain`直接替换成`span`后，二级标题反而正常了（预览和导出都正常）。

**Comment by liangjingkanji** [comment]
超链接应该会出问题

**Comment by liangjingkanji** [comment]
Duplicate of typora/typora-issues#4643

**Comment by letonshift** [comment]
是否可以使用text-decoration? 我是新手，这样写看起来差不多、导出时也能渲染。不知道有什么缺点吗? @liangjingkanji @moulai 
```css
h2 {
    font-size: 1.8rem;
    text-decoration-line: underline;
    text-underline-offset: 0.8rem;
}
```
