### ISSUE TITLE
问题反馈：字体加粗不生效

### ISSUE THREAD

**Issue by k650dg4d2** [liangjingkanji/DrakeTyporaTheme#86]
### 描述问题
字体加粗不生效没有效果。

### 截图
![QQ截图20220509170223](https://user-images.githubusercontent.com/32454224/167377920-8d2885e8-77de-442c-9ce0-fb5040c39436.png)

![QQ截图20220509170339](https://user-images.githubusercontent.com/32454224/167377748-c929c161-7b69-4aaf-a930-b648644b61ea.png)

### 系统 (建议使用最新Typora版本)
 - OS：win10 2004企业版
 - Theme ：drake
 - Typora Version：1.2.5

**Comment by liangjingkanji** [comment]
请在JetBrains后面设置一个中文字体

**Comment by liangjingkanji** [comment]
或者你把主题中的下面这个属性删除试下效果
```css
-webkit-font-smoothing: subpixel-antialiased;
```

**Comment by k650dg4d2** [comment]
> 或者你把主题中的下面这个属性删除试下效果
> 
> ```css
> -webkit-font-smoothing: subpixel-antialiased;
> ```

删了，不管用，还是那样

**Comment by liangjingkanji** [comment]
那你就换字体试试吧

**Comment by k650dg4d2** [comment]
> 请在`JetBrains Mono`后面设置一个中文字体, 否则会自动使用你的默认中文字体不太确定是什么字体

谢谢东哥，这样就可以了

**Comment by liangjingkanji** [comment]
那行

**Comment by k650dg4d2** [comment]
东哥，打扰了。我找到问题所在了，但是不知道为什么会这样。想请教您一下。
是因为我电脑替换默认字体成了苹方，现在就在调用默认的苹方bold字体。但是加粗的时候这个字体没被加粗，这个是什么原因呢，是bold字体不能被加粗还是别的什么原因啊。能不能通过css文件修改调用加粗时的字体，我想让它调用加粗字体的时候调用苹方heavy字体，不知道能不能实现。给东哥请安了

**Comment by liangjingkanji** [comment]
定义字体样式@face的时候font-weight使用`Heavy`
```css
@font-face{
    font-family: 'HYZhengYuan';
    src: local('HYZhengYuan-Heavy');
    font-display: swap;
    font-weight: bold;
    font-style: normal;
}
```
如果这个无效那我也没办法
