### ISSUE TITLE
图片适配

### ISSUE THREAD

**Issue by Machine-gun-dadadadadadada** [liangjingkanji/DrakeTyporaTheme#87]
### 描述问题
给图片添加个性化效果，已给star

### 如何复现问题
可以给图片设置边框，或设置圆角样式

### 期望结果
![image](https://user-images.githubusercontent.com/83322025/169853438-f849b288-4c70-4c96-9eb7-cd9e1106b1ff.png)

### 截图
截图如上

### 系统 (建议使用最新Typora版本)
 - OS windows
 - Theme vue
 - Typora Version 1.2.5

**Comment by liangjingkanji** [comment]
大部分人写文章都是希望图片沉浸式在文字中吧

你这个效果我不太会实现, 如果你能实现我可以放到[常见问题](https://github.com/liangjingkanji/DrakeTyporaTheme/blob/master/issues.md)提供修改思路

**Comment by liangjingkanji** [comment]
找到对应主题`drake**.css`中的`img{...}`标签替换为以下内容
```css
img {
    background: rgba(0, 0, 0, 0);
    border: none;
    box-shadow: 1px 1px 5px rgba(171, 171, 171, 0.36);
    padding: 10px;
    border-radius: 4px;
}
```
